### ISSUE TITLE
Фидбек на домашку №2

### ISSUE THREAD

**Issue by tiny-kottan** [imbaniac/Kottans-JS-2016#5]
1. Mix of tabs and spaces - use either, but don't mix
2. Wrong logic in jsClasses matching – what happens if we write site for music instruments [pakhavajs-big](http://findwords.info/term/pakhavajs) class?
3. `data-js="cool   "` featuring multiple unnecessary whitespaces – can we somehow fix that?
4. Question of personal preferences, but could use `const` over `let` and 

``````
let okClasses = classes.filter(cls=>{
    return !pattern.test(cls)
})
``` -> `classes.filter(cls => !pattern.test(cls))`
``````

**Comment by imbaniac** [comment]
[Fixed](https://github.com/imbaniac/Kottans-JS-2016/blob/master/week01/task02/index.js)
